require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/interests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Interest. As you add validations to Interest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Interest.create! valid_attributes
      get interests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      interest = Interest.create! valid_attributes
      get interest_url(interest)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_interest_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      interest = Interest.create! valid_attributes
      get edit_interest_url(interest)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Interest" do
        expect {
          post interests_url, params: { interest: valid_attributes }
        }.to change(Interest, :count).by(1)
      end

      it "redirects to the created interest" do
        post interests_url, params: { interest: valid_attributes }
        expect(response).to redirect_to(interest_url(Interest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Interest" do
        expect {
          post interests_url, params: { interest: invalid_attributes }
        }.to change(Interest, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post interests_url, params: { interest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested interest" do
        interest = Interest.create! valid_attributes
        patch interest_url(interest), params: { interest: new_attributes }
        interest.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the interest" do
        interest = Interest.create! valid_attributes
        patch interest_url(interest), params: { interest: new_attributes }
        interest.reload
        expect(response).to redirect_to(interest_url(interest))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        interest = Interest.create! valid_attributes
        patch interest_url(interest), params: { interest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested interest" do
      interest = Interest.create! valid_attributes
      expect {
        delete interest_url(interest)
      }.to change(Interest, :count).by(-1)
    end

    it "redirects to the interests list" do
      interest = Interest.create! valid_attributes
      delete interest_url(interest)
      expect(response).to redirect_to(interests_url)
    end
  end
end
